[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.11"
axum = "0.7.7"
dotenv = "0.15.0"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1.41.0", features = ["full"] }
